# Generated by Django 5.1.5 on 2025-01-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
