# Generated by Django 5.1.5 on 2025-01-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
    ]
